DocumentOnline/Controllers/InvoiceController.cs
using DocumentOnline.Helpers;
using DocumentOnline.Logics;
using DocumentOnline.ViewModels;
using Ionic.Zip;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;

namespace DocumentOnline.Controllers
{
    public class InvoiceController : Controller
    {
        private DataContext db;
        private InvoiceLogic invoiceLogic;
        private UserLogic userLogic;

        public InvoiceController()
        {
            db = new DataContext();
            invoiceLogic = new InvoiceLogic(db);
            userLogic = new UserLogic(db);
        }

        [AuthorizeUser]
        public ActionResult Index()
        {
            ViewBag.IsAdmin = this.IsAdmin();
            return View();
        }

        [HttpPost]
        [AuthorizeUser]
        public JsonResult GetData(DataTableParameter parameter)
        {
            var currentUser = this.GetCurrentUser();

            var result = invoiceLogic.GetListDataTable(currentUser.Id, parameter);

            return Json(result);
        }

        [AuthorizeUser("SuperAdmin", "Admin")]
        public ActionResult Upload()
        {
            ViewBag.IsAdmin = this.IsAdmin();
            ViewBag.UserList = userLogic.GetListSuperUserAndUser();
            return View();
        }

        [HttpPost]
        [AuthorizeUser("SuperAdmin", "Admin")]
        public JsonResult UploadFiles()
        {
            var result = new List<string>();

            if (Request.Files.Count == 0)
            {
                result.Add("Belum ada file yang dipilih");
                return Json(result);
            }

            var currentUser = this.GetCurrentUser();

            var userId = Request.Form.Get("UserId").ToGuid();
            var remarks = Request.Form.Get("Remarks").Stringify();

            var userDocumentFolder = "";
            if (userId.IsGuidNotEmpty())
            {
                var user = userLogic.Get(userId);
                if (user != null) userDocumentFolder = user.DocumentFolder;
            }
            else userDocumentFolder = currentUser.DocumentFolder;

            foreach (var item in Request.Files)
            {
                try
                {
                    var file = Request.Files[item.ToString()];

                    var fileName = Path.GetFileName(file.FileName);
                    var fileNameWithoutExtension = Path.GetFileNameWithoutExtension(file.FileName);
                    var systemFileName = FileHelper.CreateSystemFileName(file.FileName);

                    var invoice = new InvoiceViewModel();
                    invoice.Date = DateTime.Now;
                    invoice.OriginalFileName = fileName;
                    invoice.SystemFileName = systemFileName;
                    invoice.Remarks = remarks;
                    invoice.UserId = userId;
                    invoiceLogic.Create(invoice, currentUser);

                    var documentFolder = this.GetDocumentFolder(userDocumentFolder, invoice.Date.Year);
                    this.SaveUploadedFile(file, documentFolder, systemFileName);

                    db.SaveChanges();

                    result.Add($"Success: File {fileName} berhasil diupload.");
                }
                catch (Exception ex)
                {
                    result.Add("Failed: " + ex.Message);
                }
            }

            return Json(result);
        }

        [HttpGet]
        [AuthorizeUser]
        public FileResult DownloadFile(Guid id)
        {
            var invoice = invoiceLogic.Get(id);

            var currentUser = this.GetCurrentUser();

            if (!this.IsAdmin())
            {
                invoice.DownloadCount += 1;
                invoiceLogic.Update(invoice, currentUser);
                db.SaveChanges();
            }

            var path = this.GetDocumentPath
                        (
                            invoice.UserDocumentFolder,
                            invoice.Date.Year,
                            invoice.SystemFileName
                        );

            if (System.IO.File.Exists(path))
            {
                var extension = Path.GetExtension(invoice.SystemFileName).Replace(".", "");
                var result = File(path, extension, invoice.OriginalFileName);
                return result;
            }
            else return this.CreateNotFoundFile(invoice.OriginalFileName);
        }

        [HttpGet]
        [AuthorizeUser]
        public FileResult DownloadFiles(string ids)
        {
            var listId = ids.Split(';');
            var stream = new MemoryStream();
            var zip = new ZipFile();

            var currentUser = this.GetCurrentUser();
            var isAdmin = this.IsAdmin();

            foreach (var item in listId)
            {
                try
                {
                    var id = item.ToGuid();
                    if (id == null) continue;

                    var invoice = invoiceLogic.Get(id.Value);

                    if (!isAdmin)
                    {
                        invoice.DownloadCount += 1;
                        invoiceLogic.Update(invoice, currentUser);
                    }

                    var path = this.GetDocumentPath
                                (
                                    invoice.UserDocumentFolder,
                                    invoice.Date.Year,
                                    invoice.SystemFileName
                                );

                    if (System.IO.File.Exists(path))
                        zip.AddFile(path, "").FileName = invoice.OriginalFileName;
                    else zip.AddEntry(invoice.OriginalFileName + ".notfound.txt", "FILE NOT FOUND");
                }
                catch { }
            }

            db.SaveChanges();

            zip.Save(stream);
            stream.Position = 0;
            return File(stream, "application/zip", $"DocumentRecapDownload_{DateTime.Now.ToString("dd.MM.yyyy.HH.mm.ss")}.zip");
        }

        [HttpPost]
        [AuthorizeAjax("SuperAdmin")]
        public JsonResult DeleteInvoice(Guid? id)
        {
            try
            {
                invoiceLogic.Delete(id);
                db.SaveChanges();
                return Json("Success");
            }
            catch (Exception ex)
            {
                return Json("Failed: " + ex.Message);
            }
        }
    }
}

DocumentOnline/Controllers/LogHistoryController.cs
using DocumentOnline.Helpers;
using DocumentOnline.Logics;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DocumentOnline.Controllers
{
    public class LogHistoryController : Controller
    {
        DataContext db;
        LogHistoryLogic logHistoryLogic;

        public LogHistoryController()
        {
            db = new DataContext();
            logHistoryLogic = new LogHistoryLogic(db);
        }

        [AuthorizeUser]
        public ActionResult Index()
        {
            ViewBag.Date = DateTime.Today.ToString("yyyy-MM-dd");
            var list = logHistoryLogic.GetList(DateTime.Today);
            return View(list);
        }

        [AuthorizeUser]
        public ActionResult Filter(DateTime? date)
        {
            if (date == null) date = DateTime.Today;

            ViewBag.Date = date.Value.ToString("yyyy-MM-dd");

            var list = logHistoryLogic.GetList(date);
            return View("Index", list);
        }
    }
}

DocumentOnline/Views/Shared/_Layout.cshtml
@{
    dynamic currentUser = Session["CurrentUser"];
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    @Styles.Render("~/AdminLTE/plugins/font-awesome/css")
    @Styles.Render("~/AdminLTE/plugins/ionicons/css")
    @Styles.Render("~/AdminLTE/dist/css")
    @Styles.Render("~/AdminLTE/dist/css/skins")
    @Styles.Render("~/Plugins/toastr/toastr.min.css")
    @Styles.Render("~/AdminLTE/bootstrap/css")
    @Styles.Render("~/AdminLTE/plugins/datatables/css")
    @Styles.Render("~/Plugins/jquery-confirm/jquery-confirm.min.css")
    @Styles.Render("~/Plugins/bootstrap-select/css/bootstrap-select.min.css")
    @Styles.Render("~/Plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css")
</head>

<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <a href="@Url.Action("Index", "Home")" class="logo">
                <span class="logo-mini">Doc</span>
                <span class="logo-lg"><b>Doc</b>Online</span>
            </a>
            <nav class="navbar navbar-static-top" role="navigation">
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Menu</span>
                </a>

                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <li class="dropdown notifications-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-bell-o"></i>
                                <span id="notificationCount" class="label label-warning"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li id="notificationHeader" class="header"></li>
                                <li>
                                    <ul id="notificationDetail" class="menu"></ul>
                                </li>
                            </ul>
                        </li>
                        <li style="margin-right:20px"></li>
                    </ul>

                </div>
            </nav>
        </header>

        <aside class="main-sidebar">
            <section class="sidebar">
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/AdminLTE/dist/img/user.svg" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p>@currentUser.Name</p>
                        <a href="#"><i class="fa fa-circle text-success"></i>@currentUser.Role</a>
                    </div>
                </div>

                <ul class="sidebar-menu">
                    <li class="header">MAIN MENU</li>

                    @if (currentUser.Role == "SuperUser")
                    {
                        <li id="left-sidebar-menu-dashboard">
                            <a href="@Url.Action("Index", "UserDashboard")">
                                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                            </a>
                        </li>
                        <li id="left-sidebar-menu-user">
                            <a href="@Url.Action("Index", "UserManagement")">
                                <i class="fa fa-user"></i> <span>User Management</span>
                            </a>
                        </li>
                    }
                    @if (currentUser.Role == "User")
                    {
                        <li id="left-sidebar-menu-dashboard">
                            <a href="@Url.Action("Index", "UserDashboard")">
                                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                            </a>
                        </li>
                    }

                    @if (currentUser.Role == "SuperAdmin")
                    {
                        <li id="left-sidebar-menu-dashboard">
                            <a href="@Url.Action("Index", "AdminDashboard")">
                                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                            </a>
                        </li>
                        <li id="left-sidebar-menu-admin">
                            <a href="@Url.Action("Index", "AdminManagement")">
                                <i class="fa fa-user-secret"></i> <span>Admin Management</span>
                            </a>
                        </li>
                        <li id="left-sidebar-menu-user">
                            <a href="@Url.Action("Index", "UserManagement")">
                                <i class="fa fa-user"></i> <span>User Management</span>
                            </a>
                        </li>
                        <li id="left-sidebar-menu-doctype">
                            <a href="@Url.Action("Index", "DocumentType")">
                                <i class="fa fa-table"></i> <span>Document Type</span>
                            </a>
                        </li>
                        <li id="left-sidebar-menu-table">
                            <a href="@Url.Action("Index", "LogHistory")">
                                <i class="fa fa-table"></i> <span>Log History</span>
                            </a>
                        </li>
                    }

                    @if (currentUser.Role == "Admin")
                    {
                        <li id="left-sidebar-menu-dashboard">
                            <a href="@Url.Action("Index", "AdminDashboard")">
                                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                            </a>
                        </li>
                        <li id="left-sidebar-menu-table">
                            <a href="@Url.Action("Index", "UserManagement")">
                                <i class="fa fa-table"></i> <span>User Management</span>
                            </a>
                        </li>

                    }

                    <li id="left-sidebar-menu-table">
                        <a href="@Url.Action("Index", "DocumentRecap")">
                            <i class="fa fa-sticky-note"></i> <span>Document Recap</span>
                        </a>
                    </li>

                    <li id="left-sidebar-menu-table">
                        <a href="@Url.Action("Index", "Invoice")">
                            <i class="fa fa-calculator"></i> <span>Invoice</span>
                        </a>
                    </li>

                    <li class="header"></li>

                    <li id="left-sidebar-menu-logout">
                        <a id="buttonLogout" href="#">
                            <i class="fa fa-lock"></i> <span>Logout</span>
                        </a>
                    </li>

                </ul>


            </section>
        </aside>
        <div class="content-wrapper">
            <section class="content-header">
                <h1>
                    @ViewBag.Title
                    <small>@ViewBag.SubTitle</small>
                </h1>
            </section>
            <section class="content">
                @RenderBody()
            </section>
        </div>
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 1.0.0
            </div>
            <strong>Copyrights &copy; @DateTime.Now.Year</strong>
        </footer>
    </div>

    @Scripts.Render("~/AdminLTE/plugins/jquery/js")
    @RenderSection("menu", required: false)
    @Scripts.Render("~/AdminLTE/bootstrap/js")
    @Scripts.Render("~/AdminLTE/plugins/slimscroll/js")
    @Scripts.Render("~/AdminLTE/plugins/fastclick/js")
    @Scripts.Render("~/Scripts/Shared/_Layout")
    @Scripts.Render("~/AdminLTE/dist/js")
    @Scripts.Render("~/Plugins/toastr/toastr.min.js")
    @Scripts.Render("~/AdminLTE/plugins/datatables/js")
    @Scripts.Render("~/Plugins/jquery-confirm/jquery-confirm.min.js");
    @Scripts.Render("~/Plugins/bootstrap-select/js/bootstrap-select.min.js");
    @Scripts.Render("~/Plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js");

    <script>
        //global function
        function formatDate(date) {
            var day = date.substring(0, 2);
            var month = date.substring(3, 5);
            var year = date.substring(6, 10);


            return [year, month, day].join('-');
        }
    </script>

    @RenderSection("scripts", required: false)

    <script>
        $(function () {
            $.ajax({
                url: "/Notification/Get",
                success: function (result) {
                    $("#notificationCount").html(result.Count);
                    $("#notificationHeader").html("Yout have " + result.Count + " new notifications.");


                    var details = "";
                    for (var key in result.Data) {
                        var detail = "<li><a href='#'><i class='text-aqua'></i></a>" + result.Data[key] + "</li>";
                        details = details + detail;
                    }

                    $("#notificationDetail").html(details);
                }
            });

            $('#buttonLogout').confirm({
                title: "Logout",
                content: "Are you sure want to logout?",
                buttons: {
                    logout: {
                        text: "Logout",
                        action: function () {
                            window.location.href = "/Home/Logout";
                        }
                    },
                    cancel: {
                        text: "Cancel"
                    }
                }
            });
        });
    </script>
</body>
</html>